### PR TITLE
Add customizable bios to profile pages

### PR DESCRIPTION
**Pull request by mkalam-alami**
Here's my shot at the feature requested at #37 !

* I made the choice to try a WYSIWYG editor (the lightweight [Trumbowyg](https://alex-d.github.io/Trumbowyg/) that seemed to fit well).
* The allowed HTML is pretty restrictive (it only allows things like links, lists and simple formatting). The server-side HTML stripping/fixing matches those restrictions and seems to be solid, though I'm not 100% sure it can't be hacked by toying with text encoding in a forged request or something.
* Bios aren't loaded by default in the big $users dictionary, we only fetch the one we need.

The database update script is as follows:
> ALTER TABLE `user` ADD `user_bio` TEXT NULL DEFAULT NULL AFTER `user_twitter`;

**EDIT: Also I haven't set a size limit, we should probably add that too.**

capture2
capture

### CODE REVIEW

**Comment by balohmatevz** [comment]
Looks good to me! 👍

**Comment by balohmatevz** [comment]
It seems as though the icons for the text editor are missing. I just did a pull on the main 1hgj website and this is what I got. You can see it for yourself on the site's user settings page.

bioimg

**Comment by mkalam-alami** [comment]
Whoops sorry, it looks like I forgot to commit the SVG icons file.

You should be able to fix this by getting icons.svg [here](https://cdn.rawgit.com/Alex-D/Trumbowyg/v2.4.2/dist/ui/icons.svg) and putting it in the /assets/ folder.

(In case you want to change the SVG path, it's set in template/usersettings.html: `$.trumbowyg.svgPath = '/assets/icons.svg';`)

**Comment by balohmatevz** [comment]
Thanks, fixed! 😄 

The data, assets, cache and custom folders are all in .gitignore, so anything placed in those will not be pushed 🙂

**Pull request merged**
